USE [master]
GO

/****** Object:  Database [dmv]    Script Date: 11/10/2020 1:27:49 PM ******/
CREATE DATABASE [dmv]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dmv', FILENAME = N'F:\sqldata\dmv.mdf' , SIZE = 32768KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dmv_log', FILENAME = N'E:\sqllog\dmv_log.ldf' , SIZE = 85888KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [dmv] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dmv].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dmv] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dmv] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dmv] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dmv] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dmv] SET ARITHABORT OFF 
GO

ALTER DATABASE [dmv] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dmv] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dmv] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dmv] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dmv] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dmv] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dmv] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dmv] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dmv] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dmv] SET  ENABLE_BROKER 
GO

ALTER DATABASE [dmv] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dmv] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dmv] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dmv] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dmv] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dmv] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dmv] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dmv] SET RECOVERY FULL 
GO

ALTER DATABASE [dmv] SET  MULTI_USER 
GO

ALTER DATABASE [dmv] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dmv] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dmv] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dmv] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dmv] SET  READ_WRITE 
GO

